# Generated by Django 3.1.5 on 2021-10-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_each_other', '0003_charity_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
