# Generated by Django 3.1.5 on 2021-10-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_each_other', '0004_charity_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charity',
            old_name='address',
            new_name='addresss',
        ),
    ]
