# Generated by Django 3.1.5 on 2021-10-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_each_other', '0005_auto_20211027_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charity',
            old_name='addresss',
            new_name='address',
        ),
    ]
